### ISSUE TITLE
上传Fir JSONObject["cert"] not found.

### ISSUE THREAD

**Issue by e9ab98e991ab** [chenyy0708/UploadApkPlugin#1]
上传报错 

获取上传凭证...
获取凭证信息成功
上传apk中...

* What went wrong:
Execution failed for task ':app:assembleWithFir'.
> JSONObject["cert"] not found.

**Comment by chenyy0708** [comment]
我明天试试fir平台，好久没上传这个平台了， 看看是不是变了

**Comment by chenyy0708** [comment]
我明天试试fir平台，好久没上传这个平台了， 看看是不是变了

**Comment by chenyy0708** [comment]
更新了2.0.1，fir.im的上传apk域名进行了改变

**Comment by e9ab98e991ab** [comment]
补充一下 这个问题是Token错误的问题。
